### ISSUE TITLE
tests not working with the default setup

### ISSUE THREAD

**Issue by samuelcolvin** [cloudflare/rustwasm-worker-template#15]
I couldn't get tests to work without:
* changing `wasm-bindgen-test = "0.2"` to `wasm-bindgen-test = "0.3"` (with v0.2 I just get `no tests to run!`)
* and, either removing `--headless` and running them manually in a browser or using `wasm-pack test --chrome --headless`

**Comment by nilslice** [comment]
Thanks! closing this for now, until we have a proper testing strategy in place for the new template currently in place.
