### ISSUE TITLE
Adding a `/` route for template

### ISSUE THREAD

**Issue by SeokminHong** [cloudflare/rustwasm-worker-template#25]
Hello 👋 

I've just tried workers with native Rust, and I'm much surprised by its blazingly fast speed! However, I was a little confused at the first trial because 404 Not found errors occurred when I tried to test.

So, in my opinion, how about adding a simple response or basic instructions for the `/` route?

**Comment by nilslice** [comment]
Hi there! I think that's a great idea and definitely an oversight on my part. Thanks for calling it out. 

If you'd like to create a PR for it, please do! Otherwise I will tend to it ASAP.

**Comment by SeokminHong** [comment]
Sure, I'll make a PR soon (maybe tonight).

I'm planning the response will be a simple plain-text like "Hello from Workers!". Do you think it is ok or there's another idea?

**Comment by nilslice** [comment]
Sounds good! thank you
